name: http-server
services:
    simple-http-server:
        image: jdkelley/simple-http-server:latest
        volumes:
            - /opt/caddy/file:/serve
        ports:
            - 81:8000
        networks:
            - caddy_net
networks:
  caddy_net:
     external: true
